name: deepaa
channels:
  - defaults
dependencies:
  - python=3.6.8
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - numpy=1.17.2
  - pandas=0.25.1
  - scipy=1.2.0
  - imageio=2.6.1
  - tensorflow-gpu=1.12.0
